language: go
go:
  - 1.13

before_install:
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls

install:
  - make deps

script:
  - make lint
  - make test

after_success:
    - $HOME/gopath/bin/goveralls -service=travis-ci

notifications:
  email: false
